version: '3.8'
services:
  order-service:
    image: szalaigeri/booking-order-service:1.0.0
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats-1:4222
    depends_on:
      - nats-1
      - nats-2
      - nats-3
    networks:
      - nats

  nats-1:
    image: nats:2.9.11-alpine
    command:
      - '--debug'
      - '--jetstream'
      - '--cluster'
      - 'nats://0.0.0.0:6222'
      - '--http_port'
      - '8222'
      - '--routes'
      - 'nats://nats-2:6222'
      - '--name'
      - 'nats-1'
      - '--cluster_name'
      - 'qmes_prod'
    ports:
      - '8222:8222'
      - '4222:4222'
    hostname: nats-node-1
    networks: ['nats']

  nats-2:
    image: nats:2.9.11-alpine
    command:
      - '--debug'
      - '--jetstream'
      - '--cluster'
      - 'nats://0.0.0.0:6222'
      - '--http_port'
      - '8222'
      - '--routes'
      - 'nats://nats-1:6222'
      - '--name'
      - 'nats-2'
      - '--cluster_name'
      - 'qmes_prod'
    ports:
      - '28222:8222'
      - '24222:4222'
    hostname: nats-node-2
    networks: ['nats']

  nats-3:
    image: nats:2.9.11-alpine
    command:
      - '--debug'
      - '--jetstream'
      - '--cluster'
      - 'nats://0.0.0.0:6222'
      - '--http_port'
      - '8222'
      - '--routes'
      - 'nats://nats-1:6222'
      - '--name'
      - 'nats-3'
      - '--cluster_name'
      - 'qmes_prod'
    ports:
      - '38222:8222'
      - '34222:4222'
    hostname: nats-node-3
    networks: ['nats']

  nats-box:
    container_name: Nats-Box
    image: natsio/nats-box:0.13.3
    depends_on:
      - nats-1
      - nats-2
      - nats-3
    stdin_open: true
    tty: true
    networks: ['nats']

networks:
  nats:
    name: nats