version: '3.5'
services:
    nats-1:
        image: nats:2.9.11-alpine
        container_name: Nats-Node-1
        command:
            - '--debug'
            - '--jetstream'
            - '--cluster'
            - 'nats://0.0.0.0:6222'
            - '--http_port'
            - '8222'
            - '--routes'
            - 'nats://nats-2:6222'
            - '--name'
            - 'nats-1'
            - '--cluster_name'
            - 'qmes_prod'
        ports:
            - '8222:8222'
            - '4222:4222'
        hostname: nats-node-1
        networks: ['nats']
    nats-2:
        image: nats:2.9.11-alpine
        container_name: Nats-Node-2
        command:
            - '--debug'
            - '--jetstream'
            - '--cluster'
            - 'nats://0.0.0.0:6222'
            - '--http_port'
            - '8222'
            - '--routes'
            - 'nats://nats-1:6222'
            - '--name'
            - 'nats-2'
            - '--cluster_name'
            - 'qmes_prod'
        ports:
            - '28222:8222'
            - '24222:4222'
        hostname: nats-node-2
        networks: ['nats']
    nats-3:
        image: nats:2.9.11-alpine
        container_name: Nats-Node-3
        command:
            - '--debug'
            - '--jetstream'
            - '--cluster'
            - 'nats://0.0.0.0:6222'
            - '--http_port'
            - '8222'
            - '--routes'
            - 'nats://nats-1:6222'
            - '--name'
            - 'nats-3'
            - '--cluster_name'
            - 'qmes_prod'
        ports:
            - '38222:8222'
            - '34222:4222'
        hostname: nats-node-3
        networks: ['nats']
    # Application Container ----------------------------------------->
#    subscriber:
#        image: andrasszalai127/subscriber:v1.0.1
#        container_name: subscriber
#        ports:
#            - '3100:3100'
#        depends_on:
#            - nats-1
#            - nats-2
#            - nats-3
#        networks: ['nats']
    # nats-box:
    #     container_name: Nats-Box
    #     image: natsio/nats-box:0.13.3
    #     depends_on:
    #         - nats-1
    #         - nats-2
    #         - nats-3
    #     command:
    #         - -c
    #         - "nats context add local --description 'Local Development' --server nats:4222 --select && /bin/sh -l"
    #     stdin_open: true
    #     tty: true
    #     networks: ['nats']

networks:
    nats:
        name: nats
