global:
  # How frequently to scrape targets by default.
  scrape_interval: 30s
  evaluation_interval: 30s

# A list of scrape configurations.
scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'order-service'

    metrics_path: '/actuator/prometheus'

    scrape_interval: 2s

    static_configs:
      - targets: ['order-service:8080']
