apiVersion: v1
kind: Service
metadata:
  name: order-service-internal
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: order-service
      targetPort: 8080
      protocol: TCP
  selector:
    app: order-service-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
spec:
  selector:
    matchLabels:
      app: order-service-app
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
        - name: "order-service"
          image: "szalaigeri/booking-order-service:1.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NATS_URL
              value: {{ .Values.nats.url }}
            - name: NATS_TOPIC
              value: {{ .Values.nats.topic }}